---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: kv-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 31400
      name: grpc
      protocol: GRPC
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kv-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - kv-gateway
  http:
  - route:
    - destination:
        host: kv
        port:
          number: 8081
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kv-destinationrule
spec:
  host: kv
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2

